from typing import overload

from typing_extensions import Self

from .OpenMaya import MDagPath, MDagPathArray, MDoubleArray, MFnDependencyNode, MIntArray, MMessage, MObject, MObjectArray, MSelectionList, MTime

class MAnimCurveClipboard:
    def __init__(self): ...
    def clear(self): ...
    def clipboardItems(self) -> MAnimCurveClipboardItemArray: ...
    @overload
    def set(self, clipboardItemArray: MAnimCurveClipboardItemArray, /): ...
    @overload
    def set(self, __clipboardItemArray: MAnimCurveClipboardItemArray, __startTime: MTime, __endTime: MTime, __startUnitlessInput: float, __endUnitlessInput: float, /, strictValidation: bool = True): ...
    __new__: Self
    endTime: MTime
    endUnitlessInput: float
    isEmpty: bool
    startTime: MTime
    startUnitlessInput: float
    theAPIClipboard: MAnimCurveClipboard

class MAnimCurveClipboardItemArray:
    def __add__(*args, **kwargs): ...
    def __contains__(*args, **kwargs): ...
    def __delitem__(*args, **kwargs): ...
    def __delslice__(*args, **kwargs): ...
    def __getitem__(*args, **kwargs): ...
    def __getslice__(*args, **kwargs): ...
    def __iadd__(*args, **kwargs): ...
    def __imul__(*args, **kwargs): ...
    def __init__(*args, **kwargs): ...
    def __len__(*args, **kwargs): ...
    def __mul__(*args, **kwargs): ...
    def __repr__(*args, **kwargs): ...
    def __rmul__(*args, **kwargs): ...
    def __setitem__(*args, **kwargs): ...
    def __setslice__(*args, **kwargs): ...
    def __str__(*args, **kwargs): ...
    def append(*args, **kwargs): ...
    def clear(*args, **kwargs): ...
    def copy(*args, **kwargs): ...
    def insert(*args, **kwargs): ...
    def remove(*args, **kwargs): ...
    def setLength(*args, **kwargs): ...
    __new__: Self
    sizeIncrement: int

class MAnimControl:
    @staticmethod
    def animationEndTime(*args, **kwargs): ...
    @staticmethod
    def animationStartTime(*args, **kwargs): ...
    @staticmethod
    def autoKeyMode(*args, **kwargs): ...
    @staticmethod
    def currentTime(*args, **kwargs): ...
    @staticmethod
    def globalInTangentType(*args, **kwargs): ...
    @staticmethod
    def globalOutTangentType(*args, **kwargs): ...
    @staticmethod
    def isPlaying(*args, **kwargs): ...
    @staticmethod
    def isScrubbing(*args, **kwargs): ...
    @staticmethod
    def maxTime(*args, **kwargs): ...
    @staticmethod
    def minTime(*args, **kwargs): ...
    @staticmethod
    def playBackward(*args, **kwargs): ...
    @staticmethod
    def playForward(*args, **kwargs): ...
    @staticmethod
    def playbackBy(*args, **kwargs): ...
    @staticmethod
    def playbackMode(*args, **kwargs): ...
    @staticmethod
    def playbackSpeed(*args, **kwargs): ...
    @staticmethod
    def setAnimationEndTime(*args, **kwargs): ...
    @staticmethod
    def setAnimationStartEndTime(*args, **kwargs): ...
    @staticmethod
    def setAnimationStartTime(*args, **kwargs): ...
    @staticmethod
    def setAutoKeyMode(*args, **kwargs): ...
    @staticmethod
    def setCurrentTime(*args, **kwargs): ...
    @staticmethod
    def setGlobalInTangentType(*args, **kwargs): ...
    @staticmethod
    def setGlobalOutTangentType(*args, **kwargs): ...
    @staticmethod
    def setMaxTime(*args, **kwargs): ...
    @staticmethod
    def setMinMaxTime(*args, **kwargs): ...
    @staticmethod
    def setMinTime(*args, **kwargs): ...
    @staticmethod
    def setPlaybackBy(*args, **kwargs): ...
    @staticmethod
    def setPlaybackMode(*args, **kwargs): ...
    @staticmethod
    def setPlaybackSpeed(*args, **kwargs): ...
    @staticmethod
    def setViewMode(*args, **kwargs): ...
    @staticmethod
    def setWeightedTangents(*args, **kwargs): ...
    @staticmethod
    def stop(*args, **kwargs): ...
    @staticmethod
    def viewMode(*args, **kwargs): ...
    @staticmethod
    def weightedTangents(*args, **kwargs): ...
    kPlaybackLoop: int = 1
    kPlaybackOnce: int = 0
    kPlaybackOscillate: int = 2
    kPlaybackViewActive: int = 1
    kPlaybackViewAll: int = 0

class MAnimUtil:
    @staticmethod
    def findAnimatablePlugs(*args, **kwargs): ...
    @staticmethod
    def findAnimatedPlugs(*args, **kwargs): ...
    @staticmethod
    def findAnimation(*args, **kwargs): ...
    @staticmethod
    def findConstraint(*args, **kwargs): ...
    @staticmethod
    def findSetDrivenKeyAnimation(*args, **kwargs): ...
    @staticmethod
    def isAnimated(*args, **kwargs): ...

class MAnimCurveClipboardItem:
    def __init__(*args, **kwargs): ...
    def animCurveType(*args, **kwargs): ...
    def getAddressingInfo(*args, **kwargs): ...
    def setAddressingInfo(*args, **kwargs): ...
    def setAnimCurve(*args, **kwargs): ...
    def setNameInfo(*args, **kwargs): ...
    __new__: Self
    animCurve: MObject
    fullAttributeName: str
    leafAttributeName: str
    nodeName: str

class MAnimCurveChange:
    def __init__(*args, **kwargs): ...
    def redoIt(*args, **kwargs): ...
    def undoIt(*args, **kwargs): ...
    __new__: Self

class MAnimMessage(MMessage):
    @staticmethod
    def addAnimCurveEditedCallback(*args, **kwargs): ...
    @staticmethod
    def addAnimKeyframeEditCheckCallback(*args, **kwargs): ...
    @staticmethod
    def addAnimKeyframeEditedCallback(*args, **kwargs): ...
    @staticmethod
    def addDisableImplicitControlCallback(*args, **kwargs): ...
    @staticmethod
    def addNodeAnimKeyframeEditedCallback(*args, **kwargs): ...
    @staticmethod
    def addPostBakeResultsCallback(*args, **kwargs): ...
    @staticmethod
    def addPreBakeResultsCallback(*args, **kwargs): ...
    @staticmethod
    def flushAnimKeyframeEditedCallbacks(*args, **kwargs): ...

class MFnGeometryFilter(MFnDependencyNode):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, object: MObject, /): ...
    def getInputGeometry(self) -> MObjectArray: ...
    def getOutputGeometry(self) -> MObjectArray: ...
    def getPathAtIndex(self, plugIndex: int, /) -> MDagPath: ...
    def groupIdAtIndex(self, plugIndex: int, /) -> int: ...
    def indexForGroupId(self, groupId: int, /) -> int: ...
    def indexForOutputConnection(self, connIndx: int, /) -> int: ...
    def indexForOutputShape(self, shape: MObject, /) -> int: ...
    def inputShapeAtIndex(self, plugIndex: int, /) -> MObject: ...
    def numOutputConnections(self) -> int: ...
    def outputShapeAtIndex(self, index: int, /) -> MObject: ...
    __new__: Self
    deformerSet: MObject
    envelope: float

class MFnAnimCurve(MFnDependencyNode):
    def __init__(*args, **kwargs): ...
    def addKey(*args, **kwargs): ...
    def addKeys(*args, **kwargs): ...
    def addKeysWithTangents(*args, **kwargs): ...
    def create(*args, **kwargs): ...
    def evaluate(*args, **kwargs): ...
    def find(*args, **kwargs): ...
    def findClosest(*args, **kwargs): ...
    def getTangentAngleWeight(*args, **kwargs): ...
    def getTangentXY(*args, **kwargs): ...
    def inTangentType(*args, **kwargs): ...
    def input(*args, **kwargs): ...
    def insertKey(*args, **kwargs): ...
    def isBreakdown(*args, **kwargs): ...
    def outTangentType(*args, **kwargs): ...
    def remove(*args, **kwargs): ...
    def setAngle(*args, **kwargs): ...
    def setInTangentType(*args, **kwargs): ...
    def setInput(*args, **kwargs): ...
    def setIsBreakdown(*args, **kwargs): ...
    def setIsWeighted(*args, **kwargs): ...
    def setOutTangentType(*args, **kwargs): ...
    def setPostInfinityType(*args, **kwargs): ...
    def setPreInfinityType(*args, **kwargs): ...
    def setTangent(*args, **kwargs): ...
    def setTangentTypes(*args, **kwargs): ...
    def setTangentsLocked(*args, **kwargs): ...
    def setValue(*args, **kwargs): ...
    def setWeight(*args, **kwargs): ...
    def setWeightsLocked(*args, **kwargs): ...
    def tangentsLocked(*args, **kwargs): ...
    def timedAnimCurveTypeForPlug(*args, **kwargs): ...
    def unitlessAnimCurveTypeForPlug(*args, **kwargs): ...
    def value(*args, **kwargs): ...
    def weightsLocked(*args, **kwargs): ...
    __new__: Self
    animCurveType: int
    isStatic: bool
    isTimeInput: bool
    isUnitlessInput: bool
    isWeighted: bool
    kAnimCurveTA: int = 0
    kAnimCurveTL: int = 1
    kAnimCurveTT: int = 2
    kAnimCurveTU: int = 3
    kAnimCurveUA: int = 4
    kAnimCurveUL: int = 5
    kAnimCurveUT: int = 6
    kAnimCurveUU: int = 7
    kAnimCurveUnknown: int = 8
    kConstant: int = 0
    kCycle: int = 3
    kCycleRelative: int = 4
    kLinear: int = 1
    kOscillate: int = 5
    kTangentAuto: int = 11
    kTangentClamped: int = 8
    kTangentCustomEnd: int = 32767
    kTangentCustomStart: int = 64
    kTangentFast: int = 7
    kTangentFixed: int = 1
    kTangentFlat: int = 3
    kTangentGlobal: int = 0
    kTangentLinear: int = 2
    kTangentPlateau: int = 9
    kTangentShared1: int = 19
    kTangentShared2: int = 20
    kTangentShared3: int = 21
    kTangentShared4: int = 22
    kTangentShared5: int = 23
    kTangentShared6: int = 24
    kTangentShared7: int = 25
    kTangentShared8: int = 26
    kTangentSlow: int = 6
    kTangentSmooth: int = 4
    kTangentStep: int = 5
    kTangentStepNext: int = 10
    kTangentTypeCount: int = 32768
    numKeys: int
    postInfinityType: int
    preInfinityType: int

class MFnSkinCluster(MFnGeometryFilter):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, object: MObject, /): ...
    def getBlendWeights(self, shape: MDagPath, components: MObject, /) -> MDoubleArray: ...
    def getPointsAffectedByInfluence(self, influence: MDagPath, /) -> tuple[MSelectionList, MDoubleArray]: ...
    @overload
    def getWeights(self, shape: MDagPath, components: MObject, /) -> tuple[MDoubleArray, int]: ...
    @overload
    def getWeights(self, shape: MDagPath, components: MObject, influence: int, /) -> MDoubleArray: ...
    @overload
    def getWeights(self, shape: MDagPath, components: MObject, influences: MIntArray, /) -> MDoubleArray: ...
    def indexForInfluenceObject(self, influenceObj: MObject, /) -> int: ...
    def influenceObjects(self) -> MDagPathArray: ...
    def setBlendWeights(self, shape: MDagPath, components: MObject, weights: MDoubleArray, /) -> Self: ...
    @overload
    def setWeights(self, __shape: MDagPath, __components: MObject, __influence: int, __weight: float, /, normalize=True, returnOldWeights=False) -> None | MDoubleArray: ...
    @overload
    def setWeights(self, __shape: MDagPath, __components: MObject, __influences: MIntArray, __weights: MDoubleArray, /, normalize=True, returnOldWeights=False) -> None | MDoubleArray: ...
    __new__: Self
